# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup SPA files
      run: ./gradlew setupSpa
      shell: bash    
    - name: Build distribution files
      run: ./gradlew build -x test
      shell: bash
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: distribution.zip
        path: ./build/distributions/*.zip
#      Add new tag and release with artifact

# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
    - uses: mukunku/tag-exists-action@v1.2.0
      id: checkTag
      with:
        tag: "${{ steps.version.outputs.data }}"

    - name: Create Release
      if: steps.checkTag.outputs.exists == 'false'
      uses: avakar/tag-and-release@v1
      with:
        tag_name: "${{ steps.version.outputs.data }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Create new release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false


